# Frozen system packages; updating the date requires repeating crypto checks.
FROM archlinux@sha256:82b1b08faae9d61e3e7e13d562f4d09114d939105b0d59ff34140f3bd418593a
RUN printf 'Server = https://archive.archlinux.org/repos/2026/09/07/$repo/os/$arch\n' > /etc/pacman.d/mirrorlist
RUN pacman -Syyu --noconfirm --needed base-devel rust leancrypto openssl sqlite python iproute2 nftables wireguard-tools procps-ng
RUN pkg-config --modversion leancrypto openssl sqlite3 && rustc --version
WORKDIR /work
