[package]
authors = [
  "Jake McGinty <me@jakebot.org>",
  "Brian Schwind <brian@tonari.no>",
  "Ryo Kawaguchi <ryo@tonari.no>",
  "Matěj Laitl <matej@tonari.no>",
]
categories = ["network-programming"]
description = "Library utilities shared between innernet (client) and innernet-server"
edition = "2021"
homepage = "https://github.com/tonarino/innernet"
keywords.workspace = true
license = "MIT"
name = "innernet-shared"
publish = true
readme = "../README.md"
repository = "https://github.com/tonarino/innernet"
version = "2.0.0"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
atty = "0.2.14"
clap = { version = "4.6.6", features = ["derive", "wrap_help"] }
colored.workspace = true
dialoguer.workspace = true
getrandom = "0.4.3"
hostsfile = { version = "2.0.0", path = "../hostsfile" }
indoc = "2.0.7"
innernet-publicip = { version = "2.0.0", path = "../publicip" }
ipnet = { version = "2.12.2", features = ["serde"] }
libc = "0.2.189"
log = "0.4.34"
once_cell = "1.21.4"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.5"
url = "2.5.8"
wireguard-control = { version = "2.0.0", path = "../wireguard-control" }
zeroize = "1.9.0"
netlink-packet-core = "0.9.0"
netlink-packet-route = "0.33.0"
netlink-request = { version = "2.0.0", path = "../netlink-request" }
netlink-sys = "0.9.0"

[features]
selinux = ["hostsfile/selinux"]
