//! Renders a standard `wg-quick`-compatible `.conf` for a non-innernet WireGuard client (e.g. a
//! phone running the stock WireGuard app), which has no way to run `innernet redeem-invite` or
//! any other innernet-native flow. See doc/design.md 5.10.
//!
//! This is deliberately a one-time, point-in-time snapshot: there is no fetch loop for a static
//! client, so any later peer add/remove/endpoint change never reaches it automatically. See
//! [`render_wg_quick_conf`]'s output header and [`parse_exported_interface`] (used to refresh an
//! already-exported file without rotating its keys) for how that limitation is surfaced.

use crate::{chmod, Error, Peer, PERSISTENT_KEEPALIVE_INTERVAL_SECS};
use anyhow::{anyhow, Context as _};
use ipnet::IpNet;
use std::{fmt::Write as _, fs::OpenOptions, io::Write as _, path::Path};

/// Renders a `wg-quick` config for a peer identified by `private_key_base64`/`address`, with one
/// `[Peer]` block per entry in `peers` (skipping disabled/not-yet-redeemed peers and the peer
/// being exported itself, identified by its derived public key).
///
/// `peers` is expected to be the same already-fetched peer list a normal `add-peer`/
/// `export-peer-config` invocation already has in hand — no separate server round trip.
pub fn render_wg_quick_conf(
    private_key_base64: &str,
    address: IpNet,
    peers: &[Peer],
) -> Result<String, Error> {
    let our_public_key = wireguard_control::Key::from_base64(private_key_base64)
        .map_err(|e| anyhow!("invalid private key: {e}"))?
        .get_public()
        .to_base64();

    let mut out = String::new();
    writeln!(
        out,
        "# Generated by innernet (add-peer --export-wg-conf / export-peer-config)."
    )?;
    writeln!(
        out,
        "# This is a POINT-IN-TIME SNAPSHOT: it will not automatically reflect future peer,"
    )?;
    writeln!(
        out,
        "# endpoint, or CIDR changes on the network. Re-run `innernet export-peer-config"
    )?;
    writeln!(
        out,
        "# <this-file>` on the admin machine to refresh the peer list without rotating this"
    )?;
    writeln!(out, "# device's keys or breaking its current tunnel.")?;
    writeln!(out)?;
    writeln!(out, "[Interface]")?;
    writeln!(out, "PrivateKey = {private_key_base64}")?;
    writeln!(out, "Address = {address}")?;
    writeln!(out)?;

    for peer in peers {
        if peer.is_disabled || !peer.is_redeemed || peer.public_key == our_public_key {
            continue;
        }

        writeln!(out, "[Peer]")?;
        writeln!(out, "# {}", peer.name)?;
        writeln!(out, "PublicKey = {}", peer.public_key)?;
        let prefix = if peer.ip.is_ipv4() { 32 } else { 128 };
        writeln!(out, "AllowedIPs = {}/{prefix}", peer.ip)?;
        if let Some(endpoint) = &peer.endpoint {
            writeln!(out, "Endpoint = {endpoint}")?;
        }
        if let Some(keepalive) = peer.persistent_keepalive_interval {
            writeln!(out, "PersistentKeepalive = {keepalive}")?;
        } else {
            writeln!(
                out,
                "PersistentKeepalive = {PERSISTENT_KEEPALIVE_INTERVAL_SECS}"
            )?;
        }
        writeln!(out)?;
    }

    Ok(out)
}

/// Extracts the private key and address from the `[Interface]` section of a config this
/// exporter itself produced (see [`render_wg_quick_conf`]), to refresh its `[Peer]` blocks
/// without generating a new keypair. **Not** a general-purpose `wg-quick` parser for arbitrary
/// third-party config files — it only understands the specific, controlled shape this module
/// writes, and stops at the first `[Peer]` section since nothing after that is needed.
pub fn parse_exported_interface(contents: &str) -> Result<(String, IpNet), Error> {
    let mut private_key = None;
    let mut address = None;

    for line in contents.lines() {
        let line = line.trim();
        if line.starts_with("[Peer]") {
            break;
        }
        if let Some(value) = parse_key_value(line, "PrivateKey") {
            private_key = Some(value.to_string());
        } else if let Some(value) = parse_key_value(line, "Address") {
            address = Some(
                value
                    .parse()
                    .with_context(|| format!("invalid Address {value:?} in exported config"))?,
            );
        }
    }

    let private_key = private_key
        .ok_or_else(|| anyhow!("no PrivateKey found in the config's [Interface] section"))?;
    let address =
        address.ok_or_else(|| anyhow!("no Address found in the config's [Interface] section"))?;
    Ok((private_key, address))
}

fn parse_key_value<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let rest = line.strip_prefix(key)?;
    rest.trim_start().strip_prefix('=').map(str::trim)
}

/// Writes an exported config to disk with the same `0o600`/owner-only discipline as every other
/// file carrying a WireGuard private key in this codebase (e.g. `InterfaceConfig::save_new`) —
/// this file is no different just because it's destined for another device.
pub fn write_exported_conf(path: &Path, contents: &str) -> Result<(), Error> {
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)
        .with_context(|| format!("failed to open {path:?} for writing"))?;
    chmod(&file, 0o600).with_context(|| format!("failed to set permissions on {path:?}"))?;
    file.write_all(contents.as_bytes())
        .with_context(|| format!("failed to write exported config to {path:?}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Hostname, PeerContents};
    use std::net::IpAddr;
    use wireguard_control::KeyPair;

    fn test_peer(
        id: i64,
        name: &str,
        ip: &str,
        public_key: &str,
        endpoint: Option<&str>,
        is_disabled: bool,
        is_redeemed: bool,
    ) -> Peer {
        Peer {
            id,
            contents: PeerContents {
                name: name.parse::<Hostname>().unwrap(),
                ip: ip.parse::<IpAddr>().unwrap(),
                cidr_id: 1,
                public_key: public_key.to_string(),
                endpoint: endpoint.map(|e| e.parse().unwrap()),
                persistent_keepalive_interval: None,
                is_admin: false,
                is_disabled,
                is_redeemed,
                invite_expires: None,
                candidates: vec![],
                rosenpass_public_key: None,
                rosenpass_public_key_hash: None,
                rosenpass_addr: None,
            },
        }
    }

    #[test]
    fn test_render_excludes_self_disabled_and_unredeemed() {
        let keypair = KeyPair::generate();
        let our_public_key = keypair.public.to_base64();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();

        let peers = vec![
            test_peer(1, "self", "10.80.0.5", &our_public_key, None, false, true),
            test_peer(
                2,
                "normal-peer",
                "10.80.0.6",
                "peer2key",
                Some("1.2.3.4:51820"),
                false,
                true,
            ),
            test_peer(
                3,
                "disabled-peer",
                "10.80.0.7",
                "peer3key",
                None,
                true,
                true,
            ),
            test_peer(
                4,
                "unredeemed-peer",
                "10.80.0.8",
                "peer4key",
                None,
                false,
                false,
            ),
        ];

        let rendered = render_wg_quick_conf(&keypair.private.to_base64(), address, &peers).unwrap();

        assert!(rendered.contains("[Interface]"));
        assert!(rendered.contains(&format!("PrivateKey = {}", keypair.private.to_base64())));
        assert!(rendered.contains("Address = 10.80.0.5/32"));

        // Only the normal, enabled, redeemed, non-self peer should appear.
        assert_eq!(rendered.matches("[Peer]").count(), 1);
        assert!(rendered.contains("normal-peer"));
        assert!(rendered.contains("peer2key"));
        assert!(rendered.contains("AllowedIPs = 10.80.0.6/32"));
        assert!(rendered.contains("Endpoint = 1.2.3.4:51820"));
        assert!(!rendered.contains("disabled-peer"));
        assert!(!rendered.contains("unredeemed-peer"));
        assert!(!rendered.contains(&our_public_key));
    }

    #[test]
    fn test_render_omits_endpoint_when_unknown() {
        let keypair = KeyPair::generate();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();
        let peers = vec![test_peer(
            2,
            "no-endpoint-peer",
            "10.80.0.6",
            "peer2key",
            None,
            false,
            true,
        )];

        let rendered = render_wg_quick_conf(&keypair.private.to_base64(), address, &peers).unwrap();
        assert!(rendered.contains("[Peer]"));
        assert!(!rendered.contains("Endpoint ="));
    }

    #[test]
    fn test_parse_exported_interface_roundtrip() {
        let keypair = KeyPair::generate();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();
        let rendered = render_wg_quick_conf(&keypair.private.to_base64(), address, &[]).unwrap();

        let (parsed_key, parsed_addr) = parse_exported_interface(&rendered).unwrap();
        assert_eq!(parsed_key, keypair.private.to_base64());
        assert_eq!(parsed_addr, address);
    }

    #[test]
    fn test_parse_exported_interface_rejects_missing_fields() {
        assert!(parse_exported_interface("[Interface]\nAddress = 10.0.0.1/32\n").is_err());
        assert!(parse_exported_interface("[Interface]\nPrivateKey = abc\n").is_err());
        assert!(parse_exported_interface("").is_err());
    }

    #[test]
    fn test_write_exported_conf_sets_owner_only_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("phone.conf");

        write_exported_conf(&path, "test contents").unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "exported config carries a private key and must be owner-only, like every other \
             file in this codebase holding a WireGuard private key"
        );
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "test contents");
    }
}
