//! Renders a standard `wg-quick`-compatible `.conf` for a non-innernet WireGuard client (e.g. a
//! phone running the stock WireGuard app), which has no way to run `innernet redeem-invite` or
//! any other innernet-native flow. See doc/design.md 5.10.
//!
//! This is deliberately a one-time, point-in-time snapshot: there is no fetch loop for a static
//! client, so any later peer add/remove/endpoint change never reaches it automatically. See
//! [`render_wg_quick_conf`]'s output header and [`parse_exported_interface`] (used to refresh an
//! already-exported file without rotating its keys) for how that limitation is surfaced.

use crate::{chmod, ensure_dirs_exist, Error, Peer, PERSISTENT_KEEPALIVE_INTERVAL_SECS};
use anyhow::{anyhow, Context as _};
use ipnet::IpNet;
use std::{
    collections::HashMap,
    fmt::Write as _,
    fs::OpenOptions,
    io::Write as _,
    path::{Path, PathBuf},
};
use wireguard_control::{Backend, DeviceUpdate, InterfaceName, Key, PeerConfigBuilder};

/// Renders a `wg-quick` config for a peer identified by `private_key_base64`/`address`, with one
/// `[Peer]` block per entry in `peers` (skipping disabled/not-yet-redeemed peers and the peer
/// being exported itself, identified by its derived public key).
///
/// `peers` is expected to be the same already-fetched peer list a normal `add-peer`/
/// `export-peer-config` invocation already has in hand — no separate server round trip.
///
/// `link_psk`, if given, is `(the exporting admin peer's own public key, a preshared key)`: the
/// `[Peer]` block matching that public key (i.e. the admin peer, from this exported peer's point
/// of view) gets a `PresharedKey` line. This is the *only* link this mechanism protects — see
/// [`apply_exported_psks`] for why, and doc/design.md 5.10 for the full rationale. Every other
/// `[Peer]` block is unaffected, exactly as before.
pub fn render_wg_quick_conf(
    private_key_base64: &str,
    address: IpNet,
    peers: &[Peer],
    link_psk: Option<(&str, &Key)>,
) -> Result<String, Error> {
    let our_public_key = wireguard_control::Key::from_base64(private_key_base64)
        .map_err(|e| anyhow!("invalid private key: {e}"))?
        .get_public()
        .to_base64();

    let mut out = String::new();
    writeln!(
        out,
        "# Generated by innernet (add-peer --export-wg-conf / export-peer-config)."
    )?;
    writeln!(
        out,
        "# This is a POINT-IN-TIME SNAPSHOT: it will not automatically reflect future peer,"
    )?;
    writeln!(
        out,
        "# endpoint, or CIDR changes on the network. Re-run `innernet export-peer-config"
    )?;
    writeln!(
        out,
        "# <this-file>` on the admin machine to refresh the peer list without rotating this"
    )?;
    writeln!(out, "# device's keys or breaking its current tunnel.")?;
    writeln!(out)?;
    writeln!(out, "[Interface]")?;
    writeln!(out, "PrivateKey = {private_key_base64}")?;
    writeln!(out, "Address = {address}")?;
    writeln!(out)?;

    for peer in peers {
        if peer.is_disabled || !peer.is_redeemed || peer.public_key == our_public_key {
            continue;
        }

        writeln!(out, "[Peer]")?;
        writeln!(out, "# {}", peer.name)?;
        writeln!(out, "PublicKey = {}", peer.public_key)?;
        let prefix = if peer.ip.is_ipv4() { 32 } else { 128 };
        writeln!(out, "AllowedIPs = {}/{prefix}", peer.ip)?;
        if let Some((admin_public_key, psk)) = link_psk {
            if peer.public_key == admin_public_key {
                writeln!(out, "PresharedKey = {}", psk.to_base64())?;
            }
        }
        if let Some(endpoint) = &peer.endpoint {
            writeln!(out, "Endpoint = {endpoint}")?;
        }
        if let Some(keepalive) = peer.persistent_keepalive_interval {
            writeln!(out, "PersistentKeepalive = {keepalive}")?;
        } else {
            writeln!(
                out,
                "PersistentKeepalive = {PERSISTENT_KEEPALIVE_INTERVAL_SECS}"
            )?;
        }
        writeln!(out)?;
    }

    Ok(out)
}

/// Extracts the private key and address from the `[Interface]` section of a config this
/// exporter itself produced (see [`render_wg_quick_conf`]), to refresh its `[Peer]` blocks
/// without generating a new keypair. **Not** a general-purpose `wg-quick` parser for arbitrary
/// third-party config files — it only understands the specific, controlled shape this module
/// writes, and stops at the first `[Peer]` section since nothing after that is needed.
pub fn parse_exported_interface(contents: &str) -> Result<(String, IpNet), Error> {
    let mut private_key = None;
    let mut address = None;

    for line in contents.lines() {
        let line = line.trim();
        if line.starts_with("[Peer]") {
            break;
        }
        if let Some(value) = parse_key_value(line, "PrivateKey") {
            private_key = Some(value.to_string());
        } else if let Some(value) = parse_key_value(line, "Address") {
            address = Some(
                value
                    .parse()
                    .with_context(|| format!("invalid Address {value:?} in exported config"))?,
            );
        }
    }

    let private_key = private_key
        .ok_or_else(|| anyhow!("no PrivateKey found in the config's [Interface] section"))?;
    let address =
        address.ok_or_else(|| anyhow!("no Address found in the config's [Interface] section"))?;
    Ok((private_key, address))
}

fn parse_key_value<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let rest = line.strip_prefix(key)?;
    rest.trim_start().strip_prefix('=').map(str::trim)
}

/// Writes an exported config to disk with the same `0o600`/owner-only discipline as every other
/// file carrying a WireGuard private key in this codebase (e.g. `InterfaceConfig::save_new`) —
/// this file is no different just because it's destined for another device.
pub fn write_exported_conf(path: &Path, contents: &str) -> Result<(), Error> {
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)
        .with_context(|| format!("failed to open {path:?} for writing"))?;
    chmod(&file, 0o600).with_context(|| format!("failed to set permissions on {path:?}"))?;
    file.write_all(contents.as_bytes())
        .with_context(|| format!("failed to write exported config to {path:?}"))?;
    Ok(())
}

/// Local-only, per-interface record of manually-generated WireGuard preshared keys protecting
/// this peer's link to one or more other peers — statically-exported non-innernet peers (a
/// phone can never run Rosenpass, so it can never get a PSK from that mechanism at all — see
/// doc/design.md 5.10), and normal invited peers too (baseline PSK protection immediately at
/// invite time, before Rosenpass, if ever enabled, takes over — see `add_peer` in
/// `client/src/main.rs`/`server/src/lib.rs`). Keyed by the other peer's stable database id, not
/// its WireGuard public key: a normal invited peer's public key changes when it redeems its
/// invitation (a freshly-generated keypair replaces the invitation's temporary one), so an
/// entry keyed by the temporary key would silently never match again — verified via a real
/// docker-tests run that this exact mismatch broke connectivity. A statically-exported peer's id
/// and public key are both permanently stable either way, so id-keying works unchanged there too.
///
/// Deliberately never sent to or read from the coordination server: a PSK is exactly as
/// sensitive as a private key, and this codebase's rule that a private key never touches the
/// server (the whole reason `export-peer-config` re-derives from a locally-held file rather than
/// a server-side lookup) applies just as much here.
fn exported_psks_path(data_dir: &Path, interface: &InterfaceName) -> PathBuf {
    data_dir
        .join("exported-psks")
        .join(format!("{interface}.toml"))
}

fn read_exported_psks(
    data_dir: &Path,
    interface: &InterfaceName,
) -> Result<HashMap<String, String>, Error> {
    let path = exported_psks_path(data_dir, interface);
    match std::fs::read_to_string(&path) {
        Ok(contents) => {
            toml::from_str(&contents).with_context(|| format!("failed to parse {path:?}"))
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(HashMap::new()),
        Err(e) => Err(e).with_context(|| format!("failed to read {path:?}")),
    }
}

fn write_exported_psks(
    data_dir: &Path,
    interface: &InterfaceName,
    psks: &HashMap<String, String>,
) -> Result<(), Error> {
    let path = exported_psks_path(data_dir, interface);
    if let Some(dir) = path.parent() {
        ensure_dirs_exist(&[dir])?;
    }
    let contents = toml::to_string(psks).context("failed to serialize exported peer PSKs")?;
    write_exported_conf(&path, &contents)
}

/// Looks up a previously-saved preshared key protecting the link to peer `peer_id`, if any -
/// `None` for a peer that was never linked this way. Keyed by the peer's stable database id,
/// *not* its WireGuard public key: a normal (non-exported) invited peer's public key changes
/// when it redeems its invitation (`update_keypair` swaps in a freshly-generated keypair and
/// registers only that with the server - the invitation's original key is a one-time bootstrap
/// identity, thrown away immediately after), so keying by the id set at invitation-creation time
/// is the only thing that still matches once that rotation happens. A statically-exported
/// (`--export-wg-conf`) peer's id and public key are both permanently stable either way, so this
/// works unchanged for that case too - verified via a real docker-tests run that public-key
/// keying silently broke connectivity for normal invited peers (the admin's own locally-saved
/// PSK entry never matched the peer's real, post-redemption public key, so it was just never
/// applied - a one-sided PSK, indistinguishable from a wrong key to WireGuard).
pub fn get_exported_psk(
    data_dir: &Path,
    interface: &InterfaceName,
    peer_id: i64,
) -> Result<Option<Key>, Error> {
    let psks = read_exported_psks(data_dir, interface)?;
    match psks.get(&peer_id.to_string()) {
        Some(b64) => Ok(Some(Key::from_base64(b64).map_err(|e| {
            anyhow!("stored preshared key for peer {peer_id} isn't valid: {e}")
        })?)),
        None => Ok(None),
    }
}

/// Persists a preshared key protecting the link between this peer and peer `peer_id` (see
/// [`get_exported_psk`] for why this is keyed by id, not public key), so it survives across
/// `innernet` invocations: reapplied on every `fetch()` (see [`apply_exported_psks`]) and
/// re-embedded, unchanged, on every `export-peer-config` refresh (never regenerated - a fresh
/// PSK on refresh would silently break the already-deployed exported peer's tunnel, exactly like
/// rotating its private key would).
pub fn save_exported_psk(
    data_dir: &Path,
    interface: &InterfaceName,
    peer_id: i64,
    psk: &Key,
) -> Result<(), Error> {
    let mut psks = read_exported_psks(data_dir, interface)?;
    psks.insert(peer_id.to_string(), psk.to_base64());
    write_exported_psks(data_dir, interface, &psks)
}

/// Applies every locally-saved exported-peer preshared key (see [`save_exported_psk`]) to the
/// live WireGuard interface, as its own follow-up `DeviceUpdate` after the main peer diff — same
/// non-disruptive pattern as `rosenpass::apply_psks` (wireguard-control merges peer settings onto
/// the existing peer rather than replacing it). A no-op if no exported peer has ever been linked
/// this way. Independent of Rosenpass entirely — a plain WireGuard PSK feature, so this runs
/// regardless of whether `--enable-rosenpass` is set.
///
/// This only ever protects the link between *this* peer (the one that ran
/// `add-peer --export-wg-conf`) and the exported peer — every other peer's link to that exported
/// peer remains plain WireGuard, since there's no mechanism here to distribute this secret PSK
/// to any peer other than the one that generated it (matching the same "never touches the
/// server" constraint noted above). For a network with Rosenpass enabled, this means an exported
/// peer still needs `--rosenpass-permissive` for connectivity from *other* peers exactly as
/// documented in the README already — this mechanism only ever improves the one link it applies
/// to, from "no PSK at all" to a real (if static, non-rotating) preshared key.
pub fn apply_exported_psks(
    interface: &InterfaceName,
    backend: Backend,
    data_dir: &Path,
    peers: &[Peer],
) -> Result<(), Error> {
    let psks = read_exported_psks(data_dir, interface)?;
    if psks.is_empty() {
        return Ok(());
    }

    let mut builders = Vec::new();
    for peer in peers {
        let Some(psk_b64) = psks.get(&peer.id.to_string()) else {
            continue;
        };
        let Ok(psk) = Key::from_base64(psk_b64) else {
            log::warn!(
                "stored preshared key for peer {} isn't valid, skipping",
                peer.id
            );
            continue;
        };
        let Ok(wg_pubkey) = Key::from_base64(&peer.public_key) else {
            continue;
        };
        builders.push(PeerConfigBuilder::new(&wg_pubkey).set_preshared_key(psk));
    }

    if !builders.is_empty() {
        DeviceUpdate::new()
            .add_peers(&builders)
            .apply(interface, backend)
            .with_context(|| interface.to_string())?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Hostname, PeerContents};
    use std::net::IpAddr;
    use wireguard_control::KeyPair;

    fn test_peer(
        id: i64,
        name: &str,
        ip: &str,
        public_key: &str,
        endpoint: Option<&str>,
        is_disabled: bool,
        is_redeemed: bool,
    ) -> Peer {
        Peer {
            id,
            contents: PeerContents {
                name: name.parse::<Hostname>().unwrap(),
                ip: ip.parse::<IpAddr>().unwrap(),
                cidr_id: 1,
                public_key: public_key.to_string(),
                endpoint: endpoint.map(|e| e.parse().unwrap()),
                persistent_keepalive_interval: None,
                is_admin: false,
                is_disabled,
                is_redeemed,
                invite_expires: None,
                candidates: vec![],
                rosenpass_public_key: None,
                rosenpass_public_key_hash: None,
                rosenpass_addr: None,
            },
        }
    }

    #[test]
    fn test_render_excludes_self_disabled_and_unredeemed() {
        let keypair = KeyPair::generate();
        let our_public_key = keypair.public.to_base64();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();

        let peers = vec![
            test_peer(1, "self", "10.80.0.5", &our_public_key, None, false, true),
            test_peer(
                2,
                "normal-peer",
                "10.80.0.6",
                "peer2key",
                Some("1.2.3.4:51820"),
                false,
                true,
            ),
            test_peer(
                3,
                "disabled-peer",
                "10.80.0.7",
                "peer3key",
                None,
                true,
                true,
            ),
            test_peer(
                4,
                "unredeemed-peer",
                "10.80.0.8",
                "peer4key",
                None,
                false,
                false,
            ),
        ];

        let rendered =
            render_wg_quick_conf(&keypair.private.to_base64(), address, &peers, None).unwrap();

        assert!(rendered.contains("[Interface]"));
        assert!(rendered.contains(&format!("PrivateKey = {}", keypair.private.to_base64())));
        assert!(rendered.contains("Address = 10.80.0.5/32"));

        // Only the normal, enabled, redeemed, non-self peer should appear.
        assert_eq!(rendered.matches("[Peer]").count(), 1);
        assert!(rendered.contains("normal-peer"));
        assert!(rendered.contains("peer2key"));
        assert!(rendered.contains("AllowedIPs = 10.80.0.6/32"));
        assert!(rendered.contains("Endpoint = 1.2.3.4:51820"));
        assert!(!rendered.contains("disabled-peer"));
        assert!(!rendered.contains("unredeemed-peer"));
        assert!(!rendered.contains(&our_public_key));
    }

    #[test]
    fn test_render_omits_endpoint_when_unknown() {
        let keypair = KeyPair::generate();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();
        let peers = vec![test_peer(
            2,
            "no-endpoint-peer",
            "10.80.0.6",
            "peer2key",
            None,
            false,
            true,
        )];

        let rendered =
            render_wg_quick_conf(&keypair.private.to_base64(), address, &peers, None).unwrap();
        assert!(rendered.contains("[Peer]"));
        assert!(!rendered.contains("Endpoint ="));
    }

    #[test]
    fn test_parse_exported_interface_roundtrip() {
        let keypair = KeyPair::generate();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();
        let rendered =
            render_wg_quick_conf(&keypair.private.to_base64(), address, &[], None).unwrap();

        let (parsed_key, parsed_addr) = parse_exported_interface(&rendered).unwrap();
        assert_eq!(parsed_key, keypair.private.to_base64());
        assert_eq!(parsed_addr, address);
    }

    #[test]
    fn test_parse_exported_interface_rejects_missing_fields() {
        assert!(parse_exported_interface("[Interface]\nAddress = 10.0.0.1/32\n").is_err());
        assert!(parse_exported_interface("[Interface]\nPrivateKey = abc\n").is_err());
        assert!(parse_exported_interface("").is_err());
    }

    #[test]
    fn test_write_exported_conf_sets_owner_only_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("phone.conf");

        write_exported_conf(&path, "test contents").unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "exported config carries a private key and must be owner-only, like every other \
             file in this codebase holding a WireGuard private key"
        );
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "test contents");
    }

    #[test]
    fn test_render_attaches_psk_only_to_matching_peer() {
        let keypair = KeyPair::generate();
        let address: IpNet = "10.80.0.5/32".parse().unwrap();
        let admin_keypair = KeyPair::generate();
        let admin_public_key = admin_keypair.public.to_base64();
        let psk = Key::generate_preshared();

        let peers = vec![
            test_peer(
                2,
                "admin",
                "10.80.0.6",
                &admin_public_key,
                Some("1.2.3.4:51820"),
                false,
                true,
            ),
            test_peer(
                3,
                "other-peer",
                "10.80.0.7",
                "peer3key",
                Some("5.6.7.8:51820"),
                false,
                true,
            ),
        ];

        let rendered = render_wg_quick_conf(
            &keypair.private.to_base64(),
            address,
            &peers,
            Some((&admin_public_key, &psk)),
        )
        .unwrap();

        assert_eq!(rendered.matches("PresharedKey").count(), 1);
        // The PresharedKey line must land in the admin's own [Peer] block, not anywhere else -
        // check it appears between "admin"'s PublicKey line and the next [Peer] section.
        let admin_block_start = rendered.find(&admin_public_key).unwrap();
        let psk_pos = rendered.find("PresharedKey").unwrap();
        let other_peer_block_start = rendered.find("peer3key").unwrap();
        assert!(admin_block_start < psk_pos && psk_pos < other_peer_block_start);
        assert!(rendered.contains(&format!("PresharedKey = {}", psk.to_base64())));
    }

    #[test]
    fn test_exported_psk_roundtrip_and_default_none() {
        let dir = tempfile::tempdir().unwrap();
        let interface: InterfaceName = "evilcorp".parse().unwrap();

        assert!(get_exported_psk(dir.path(), &interface, 1)
            .unwrap()
            .is_none());

        let psk = Key::generate_preshared();
        save_exported_psk(dir.path(), &interface, 1, &psk).unwrap();

        let read_back = get_exported_psk(dir.path(), &interface, 1)
            .unwrap()
            .unwrap();
        assert_eq!(read_back.to_base64(), psk.to_base64());

        // A different peer id must not see this one's PSK.
        assert!(get_exported_psk(dir.path(), &interface, 2)
            .unwrap()
            .is_none());
    }

    #[test]
    fn test_exported_psks_file_is_owner_only() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir().unwrap();
        let interface: InterfaceName = "evilcorp".parse().unwrap();

        save_exported_psk(dir.path(), &interface, 1, &Key::generate_preshared()).unwrap();

        let path = exported_psks_path(dir.path(), &interface);
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "exported-peer PSK store holds secret preshared keys and must be owner-only"
        );
    }

    #[test]
    fn test_save_exported_psk_overwrites_existing_entry() {
        let dir = tempfile::tempdir().unwrap();
        let interface: InterfaceName = "evilcorp".parse().unwrap();

        save_exported_psk(dir.path(), &interface, 1, &Key::generate_preshared()).unwrap();
        let second = Key::generate_preshared();
        save_exported_psk(dir.path(), &interface, 1, &second).unwrap();

        let read_back = get_exported_psk(dir.path(), &interface, 1)
            .unwrap()
            .unwrap();
        assert_eq!(read_back.to_base64(), second.to_base64());
    }

    #[test]
    fn test_apply_exported_psks_is_noop_with_no_saved_psks() {
        let dir = tempfile::tempdir().unwrap();
        let interface: InterfaceName = "evilcorp".parse().unwrap();

        // No rosenpass/wireguard interface exists in this test environment - if this weren't a
        // no-op, it would fail trying to reach a real device. Confirms the empty-map fast path.
        let peers = vec![test_peer(
            1,
            "peer",
            "10.80.0.6",
            "peer1key",
            None,
            false,
            true,
        )];
        apply_exported_psks(&interface, Backend::Userspace, dir.path(), &peers).unwrap();
    }

    #[test]
    fn test_apply_exported_psks_matches_by_peer_id_not_public_key() {
        // The exact bug this keying scheme fixes: a normal invited peer's public key changes
        // when it redeems (a fresh keypair is registered, replacing the invitation's temporary
        // one) - the peer_id doesn't. A store keyed by the stale public key would never match
        // the peer's real, current entry; verified here that keying by id does.
        let dir = tempfile::tempdir().unwrap();
        let interface: InterfaceName = "evilcorp".parse().unwrap();
        let psk = Key::generate_preshared();
        save_exported_psk(dir.path(), &interface, 1, &psk).unwrap();

        let peers = vec![test_peer(
            1,
            "peer",
            "10.80.0.6",
            &KeyPair::generate().public.to_base64(), // a different key than at save time
            None,
            false,
            true,
        )];

        // No real WireGuard interface exists in this test environment, so a match would try to
        // apply a DeviceUpdate and fail - assert on the error message rather than success, to
        // distinguish "found the entry and tried to apply it" from "never found it at all".
        let err = apply_exported_psks(&interface, Backend::Userspace, dir.path(), &peers)
            .unwrap_err()
            .to_string();
        assert!(
            err.contains("evilcorp"),
            "expected a device-apply error (proving the id-keyed entry was found and matched), got: {err}"
        );
    }
}
